name: py35
dependencies:
- pip
- python
- readline
- setuptools
- sqlite
- tk
- wheel
- xz
- zlib
- numpy
- pip:
    - click
    - eventlet
    - flask-socketio
    - future
    - jinja2
    - plotlywrapper
    - pylint
    - pytest
    - pytest-cov
    - pytest-pylint
    - sphinx
    - sphinx_rtd_theme
